services:
  bot:
    build: .
    container_name: trash_bot
    environment:
      - PORT=8020
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TELEGRAM_APITOKEN=${TELEGRAM_APITOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "8020:8020"
    restart: always

