services:
  bot:
    build: .
    container_name: trash_bot
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=
      - TELEGRAM_APITOKEN=${TELEGRAM_APITOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "8080:8080"
    restart: always

