services:
  bot:
    build: .
    container_name: trash_bot
    environment:
      - TELEGRAM_APITOKEN=${TELEGRAM_APITOKEN}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    ports:
      - "8080:8080"
