telegram:
  botkey: "6317398679:AAE5pVghUpRGGagOsxebvlT3IqTOmcWXaxA"

server:
  enabled: true
  addr: "0.0.0.0"
  port: "8080"
  adminlogin: "admin"
  adminpassword: "admin"
  jwtsecret: "your-secret-key-change-in-production"

database:
  type: "sqlite"
  path: "data/trash.db"
